// src/components/VilleDetails/components/PollenInfo.tsx
export type Pollen = {
    resp: string;
    code_qual : number;
}

export default function PollenInfo({ pollen }: { pollen: Pollen }) {
    const pollenLevels = ["Indisponible", "Très faible", "Faible", "Modéré", "Élevé", "Très élevé", "Extrêmement élevé"];
    const pollenDescription = pollen !== null ? pollenLevels[pollen.code_qual] : pollenLevels[0];

    return <p className="no-margin">🌿 Pollen : <strong>{pollen.code_qual}</strong> <small className="capitalize">{pollenDescription} ({pollen.resp.toLocaleLowerCase()})</small></p>;
}

// src/lib/components/pollenInfo.svelte
<script>
    const { pollen } = $props();
    const pollenLevels = ["Indisponible", "Très faible", "Faible", "Modéré", "Élevé", "Très élevé", "Extrêmement élevé"];
    const description = pollen !== null ? pollenLevels[pollen.code_qual] : pollenLevels[0];
</script>

<p class="no-margin">🌿 Pollen :
    {#if pollen}
        <strong>{pollen.code_qual}</strong> <small class="capitalize">{description} ({pollen.resp.toLocaleLowerCase()})</small>
    {:else}
        <em>n.c</em>
    {/if}
</p>
